name: Bump Version and Tag

on:
  workflow_dispatch:
    inputs:
      bump:
        description: "Version bump type (major, minor, patch)"
        required: true
        default: "patch"

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Bump and tag version
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: "v"
          default_bump: ${{ github.event.inputs.bump }}

      - name: Push new tag to GitHub
        run: |
          echo "Created tag: ${{ steps.tag_version.outputs.new_tag }}"
